name: CI

on:
  push:
    branches: [develop]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ci:
    uses: sweetrpg/github-actions/.github/workflows/swift-ci.yaml@master
    with:
      swift-version: "6.3.3"
    secrets: inherit
